import GeodesicsDifferentiableStructure.AdmissibleClass

namespace HautevilleHouse
namespace GeometriesDifferentiableStructureCanonicalLaneLean

end GeometriesDifferentiableStructureCanonicalLaneLean
end HautevilleHouse